#ifndef _PLY_HEAD_H_FILE_
#define _PLY_HEAD_H_FILE_


#define PlyHeadP \
"\
ply \n\
format ascii 1.0 \n\
comment generated by Wei \n\
element vertex %d \n\
property float x \n\
property float y \n\
property float z \n\
end_header \n\
"

#define PlyHeadPN \
"\
ply \n\
format ascii 1.0 \n\
comment generated by Wei \n\
element vertex %d \n\
property float x \n\
property float y \n\
property float z \n\
property float nx \n\
property float ny \n\
property float nz \n\
end_header \n\
"


#define PlyHeadPC \
"\
ply \n\
format ascii 1.0 \n\
comment generated by Wei \n\
element vertex %d \n\
property float x \n\
property float y \n\
property float z \n\
property uchar red \n\
property uchar green \n\
property uchar blue \n\
end_header \n\
"


#define PlyHeadPNC \
"\
ply \n\
format ascii 1.0 \n\
comment generated by Wei \n\
element vertex %d \n\
property float x \n\
property float y \n\
property float z \n\
property float nx \n\
property float ny \n\
property float nz \n\
property uchar red \n\
property uchar green \n\
property uchar blue \n\
end_header \n\
"

#endif // !_PLY_HEAD_H_FILE_

